# Generated by Django 4.0.3 on 2022-09-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_tbl_designations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_designations',
            name='departments',
            field=models.CharField(max_length=100),
        ),
    ]
