# Generated by Django 4.0.3 on 2022-09-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_tbl_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('assets_name', models.CharField(max_length=100)),
                ('assets_id', models.CharField(max_length=100)),
                ('mouse_id', models.CharField(max_length=100)),
                ('keyboard_id', models.CharField(max_length=100)),
                ('assets_info', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
