# Generated by Django 4.0.3 on 2022-09-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_tbl_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_employee',
            old_name='martial_status',
            new_name='marital_status',
        ),
    ]
