# Generated by Django 4.0.3 on 2022-09-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_rename_martial_status_tbl_employee_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_employee',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
